pipeline {
    agent any
//    node {
        stages {
            // stage('Checkout') {
            //     steps {
            //         git branch: 'main', url: 'https://github.com/stevegregev/matrix-exercise.git'
            //     }
            // }
            
            stage('Build and push') {
                steps {
                    dir ("jenkins") {
                        script {
                            def build = docker.build("steveregev/demo/$JOB_BASE_NAME:$BUILD_NUMBER", "--build-arg prod_name=$JOB_BASE_NAME --build-arg build_num=$BUILD_NUMBER -t steveregev/demo/$JOB_BASE_NAME:$BUILD_NUMBER .")
                            docker.withRegistry('', 'docker_login') {
                                build.push()
                                build.push('latest')
                            }
                        }
                    }
                }
            }
        }
//    }
}