apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: matrix-exercise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80