pipeline {
    agent any

    environment {
        DOCKERHUB_USER = 'steveregev'
    }

    stages {
        stage('Build and push') {
            steps {
                dir ("ci") {
                    script {
                        def build = docker.build("$DOCKERHUB_USER/$JOB_BASE_NAME:$BUILD_NUMBER", "--build-arg prod_name=$JOB_BASE_NAME --build-arg build_num=$BUILD_NUMBER -t $DOCKERHUB_USER/$JOB_BASE_NAME:$BUILD_NUMBER .")
                        docker.withRegistry('', 'docker_login') {
                            build.push()
                            build.push('latest')
                        }
                    }
                }
            }
        }

        stage('Update deployment') {
            steps {
                dir ("cd") {
                    script {
                        editYaml('Deployment.yaml') { yaml ->
                            yaml.spec.template.spec.containers[0].image = "$DOCKERHUB_USER/$JOB_BASE_NAME:$BUILD_NUMBER"
                        }
                        withCredentials([gitUsernamePassword(credentialsId: 'github_user_pass', gitToolName: 'Default')]) {
                            sh '''
                                git add Deployment.yaml
                                git commit -m "Update image tag to $BUILD_NUMBER"
                                git push origin HEAD:main

                            '''
                        }
                    }
                }
            }
        }
    }
}

def editYaml (path, Closure cl) {
    def yaml = readYaml file: path
    cl.call(yaml)
    writeYaml file: path, data: yaml, overwrite: true
}